python3: can't open file '/home/runner/work/self-heal-CI-CD/self-heal-CI-CD/bug.py': [Errno 2] No such file or directory
